check if sender id is defined
TypeError: Cannot read property &#39;id&#39; of undefined<br> &nbsp; &nbsp;at preprocessEvent (C:\Users\Vladas\Projects\quiz\echo-bot\node_modules\botpress-messenger\bin\webpack:\src\incoming.js:17:20)<br> &nbsp; &nbsp;at Messenger.&lt;anonymous&gt; (C:\Users\Vladas\Projects\quiz\echo-bot\node_modules\botpress-messenger\bin\webpack:\src\incoming.js:167:5)<br> &nbsp; &nbsp;at Messenger.EventEmitter.emit (C:\Users\Vladas\Projects\quiz\echo-bot\node_modules\eventemitter2\lib\eventemitter2.js:328:19)<br> &nbsp; &nbsp;at Messenger._handleEvent (C:\Users\Vladas\Projects\quiz\echo-bot\node_modules\botpress-messenger\bin\webpack:\src\messenger.js:542:10)<br> &nbsp; &nbsp;at C:\Users\Vladas\Projects\quiz\echo-bot\node_modules\botpress-messenger\bin\webpack:\src\messenger.js:650:18<br> &nbsp; &nbsp;at Array.forEach (native)<br> &nbsp; &nbsp;at C:\Users\Vladas\Projects\quiz\echo-bot\node_modules\botpress-messenger\bin\webpack:\src\messenger.js:629:25<br> &nbsp; &nbsp;at Array.forEach (native)<br> &nbsp; &nbsp;at C:\Users\Vladas\Projects\quiz\echo-bot\node_modules\botpress-messenger\bin\webpack:\src\messenger.js:624:18<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\Users\Vladas\Projects\quiz\echo-bot\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (C:\Users\Vladas\Projects\quiz\echo-bot\node_modules\express\lib\router\route.js:137:13)<br> &nbsp; &nbsp;at Route.dispatch (C:\Users\Vladas\Projects\quiz\echo-bot\node_modules\express\lib\router\route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\Users\Vladas\Projects\quiz\echo-bot\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at C:\Users\Vladas\Projects\quiz\echo-bot\node_modules\express\lib\router\index.js:281:22<br> &nbsp; &nbsp;at Function.process_params (C:\Users\Vladas\Projects\quiz\echo-bot\node_modules\express\lib\router\index.js:335:12)<br> &nbsp; &nbsp;at next (C:\Users\Vladas\Projects\quiz\echo-bot\node_modules\express\lib\router\index.js:275:10)<br> &nbsp; &nbsp;at C:\Users\Vladas\Projects\quiz\echo-bot\node_modules\body-parser\lib\read.js:125:5<br> &nbsp; &nbsp;at invokeCallback (C:\Users\Vladas\Projects\quiz\echo-bot\node_modules\raw-body\index.js:224:16)<br> &nbsp; &nbsp;at done (C:\Users\Vladas\Projects\quiz\echo-bot\node_modules\raw-body\index.js:213:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (C:\Users\Vladas\Projects\quiz\echo-bot\node_modules\raw-body\index.js:273:7)<br> &nbsp; &nbsp;at emitNone (events.js:86:13)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:185:7)